export interface CaseItem {
  id: string;
  industry: string;
  headline: string;
  metric?: string;
  category: string;
  real?: boolean;
  date: string;
}

export const cases: CaseItem[] = [
  // ── 실제 구축 사례 (real: true) ──────────────────────────────
  {
    id: "1",
    industry: "온라인 강의 사업",
    headline: "강의 판매·결제 사이트를 통째로 자동화",
    metric: "2주 만에 오픈",
    category: "웹·앱",
    real: true,
    date: "2026-06-10",
  },
  {
    id: "2",
    industry: "리드 기반 자영업",
    headline: "고객 문의 자동응대를 AI 직원에게 맡김",
    metric: "몇 시간 → 1분, 누락 0건",
    category: "챗봇",
    real: true,
    date: "2026-06-05",
  },
  {
    id: "3",
    industry: "컨설팅펌",
    headline: "사업계획서 초안 자동 생성",
    metric: "반나절 → 10분",
    category: "문서 자동화",
    real: true,
    date: "2026-05-28",
  },
  {
    id: "4",
    industry: "제조업",
    headline: "투자유치 IR 자료를 AI로 정리",
    metric: "2억 자금 확보",
    category: "문서 자동화",
    real: true,
    date: "2026-05-20",
  },
  {
    id: "5",
    industry: "AI 교육",
    headline: "비개발자 20명에게 AI 자동화 배포",
    metric: "완주율 100%",
    category: "AI 직원팀",
    real: true,
    date: "2026-05-12",
  },

  // ── 업종별 적용 사례 (real: false) ───────────────────────────
  {
    id: "6",
    industry: "보습학원",
    headline: "수강 문의·상담 예약을 자동응대",
    metric: "야간 문의 0건 누락",
    category: "챗봇",
    real: false,
    date: "2026-05-08",
  },
  {
    id: "7",
    industry: "동네 카페",
    headline: "단골 주문·취향을 기억하는 챗봇 운영",
    metric: "재방문 안내 자동",
    category: "챗봇",
    real: false,
    date: "2026-05-07",
  },
  {
    id: "8",
    industry: "피부과 의원",
    headline: "진료 예약·변경을 카카오로 자동화",
    metric: "예약 전화 절반으로",
    category: "업무 자동화",
    real: false,
    date: "2026-05-06",
  },
  {
    id: "9",
    industry: "인테리어 시공사",
    headline: "견적 요청서를 자동으로 정리·분류",
    metric: "견적 누락 0건",
    category: "업무 자동화",
    real: false,
    date: "2026-05-04",
  },
  {
    id: "10",
    industry: "온라인 쇼핑몰",
    headline: "주문·배송 문의를 AI 직원이 1차 응대",
    metric: "응대 대기 90% 감소",
    category: "AI 직원팀",
    real: false,
    date: "2026-05-02",
  },
  {
    id: "11",
    industry: "수공예 공방",
    headline: "원데이 클래스 예약을 자동화",
    metric: "예약 정리 자동",
    category: "업무 자동화",
    real: false,
    date: "2026-04-29",
  },
  {
    id: "12",
    industry: "헬스장",
    headline: "회원 등록·만료 안내를 자동 발송",
    metric: "재등록 안내 누락 0건",
    category: "업무 자동화",
    real: false,
    date: "2026-04-27",
  },
  {
    id: "13",
    industry: "세무사 사무소",
    headline: "고객 자료 요청·수취를 자동화",
    metric: "자료 수취 자동 정리",
    category: "업무 자동화",
    real: false,
    date: "2026-04-24",
  },
  {
    id: "14",
    industry: "부동산 중개사무소",
    headline: "매물 문의를 AI가 24시간 응대",
    metric: "야간 문의 0건 누락",
    category: "챗봇",
    real: false,
    date: "2026-04-22",
  },
  {
    id: "15",
    industry: "동네 음식점",
    headline: "예약·포장 주문을 자동으로 접수",
    metric: "주문 정리 자동",
    category: "업무 자동화",
    real: false,
    date: "2026-04-20",
  },
  {
    id: "16",
    industry: "미용실",
    headline: "단골 예약·취향을 기억하는 챗봇",
    metric: "노쇼 안내 자동",
    category: "챗봇",
    real: false,
    date: "2026-04-17",
  },
  {
    id: "17",
    industry: "어학원",
    headline: "레벨테스트 접수·결과 안내를 자동화",
    metric: "접수 처리 자동",
    category: "업무 자동화",
    real: false,
    date: "2026-04-15",
  },
  {
    id: "18",
    industry: "베이커리",
    headline: "예약 케이크 주문서를 자동 정리",
    metric: "주문 누락 0건",
    category: "업무 자동화",
    real: false,
    date: "2026-04-13",
  },
  {
    id: "19",
    industry: "치과 의원",
    headline: "진료 안내·예약 확인을 AI가 응대",
    metric: "전화 응대 부담 감소",
    category: "챗봇",
    real: false,
    date: "2026-04-10",
  },
  {
    id: "20",
    industry: "꽃집",
    headline: "주문·배송 일정을 자동으로 정리",
    metric: "기념일 안내 자동",
    category: "업무 자동화",
    real: false,
    date: "2026-04-08",
  },
  {
    id: "21",
    industry: "자동차 정비소",
    headline: "정비 예약·점검 안내를 자동화",
    metric: "예약 누락 0건",
    category: "업무 자동화",
    real: false,
    date: "2026-04-06",
  },
  {
    id: "22",
    industry: "법무사 사무소",
    headline: "상담 접수·서류 안내를 AI 직원이 처리",
    metric: "1차 상담 자동 분류",
    category: "AI 직원팀",
    real: false,
    date: "2026-04-03",
  },
  {
    id: "23",
    industry: "온라인 클래스 플랫폼",
    headline: "수강생 문의를 AI가 24시간 응대",
    metric: "야간 문의 0건 누락",
    category: "챗봇",
    real: false,
    date: "2026-04-01",
  },
  {
    id: "24",
    industry: "카페 프랜차이즈",
    headline: "지점별 매출·재고를 자동 정리",
    metric: "정산 자동화",
    category: "업무 자동화",
    real: false,
    date: "2026-03-30",
  },
  {
    id: "25",
    industry: "필라테스 스튜디오",
    headline: "수업 예약·대기를 자동으로 관리",
    metric: "대기 안내 자동",
    category: "업무 자동화",
    real: false,
    date: "2026-03-27",
  },
  {
    id: "26",
    industry: "동물병원",
    headline: "예방접종·검진 시기를 자동 안내",
    metric: "재방문 안내 누락 0건",
    category: "업무 자동화",
    real: false,
    date: "2026-03-25",
  },
  {
    id: "27",
    industry: "디자인 스튜디오",
    headline: "프로젝트 견적서를 자동 생성",
    metric: "견적 작성 30분 → 5분",
    category: "문서 자동화",
    real: false,
    date: "2026-03-23",
  },
  {
    id: "28",
    industry: "공유오피스",
    headline: "입주 문의·투어 예약을 자동화",
    metric: "문의 응대 자동",
    category: "챗봇",
    real: false,
    date: "2026-03-20",
  },
  {
    id: "29",
    industry: "쇼핑몰 셀러",
    headline: "상품 상세페이지 문구를 AI로 작성",
    metric: "등록 시간 절반으로",
    category: "문서 자동화",
    real: false,
    date: "2026-03-18",
  },
  {
    id: "30",
    industry: "이사·청소 업체",
    headline: "견적 문의를 AI가 자동 응대·접수",
    metric: "야간 문의 0건 누락",
    category: "챗봇",
    real: false,
    date: "2026-03-16",
  },
  {
    id: "31",
    industry: "수입 식자재 유통",
    headline: "거래처 주문·재고를 자동으로 정리",
    metric: "주문 정리 자동",
    category: "업무 자동화",
    real: false,
    date: "2026-03-13",
  },
  {
    id: "32",
    industry: "온라인 교육 사업",
    headline: "결제·수강 안내 페이지를 직접 구축",
    metric: "랜딩·결제 한 번에",
    category: "웹·앱",
    real: false,
    date: "2026-03-11",
  },
  {
    id: "33",
    industry: "스타트업",
    headline: "투자 IR·회사소개서를 AI로 정리",
    metric: "초안 반나절 → 10분",
    category: "문서 자동화",
    real: false,
    date: "2026-03-09",
  },
  {
    id: "34",
    industry: "소규모 제조사",
    headline: "사내 문서·매뉴얼을 묻는 AI 직원 배치",
    metric: "자료 검색 즉시",
    category: "AI 직원팀",
    real: false,
    date: "2026-03-06",
  },
  {
    id: "35",
    industry: "마케팅 대행사",
    headline: "보고서·제안서를 AI로 초안 작성",
    metric: "작성 시간 70% 단축",
    category: "문서 자동화",
    real: false,
    date: "2026-03-04",
  },
  {
    id: "36",
    industry: "체험형 공방·카페",
    headline: "예약·문의를 하나의 AI 챗봇으로 통합",
    metric: "야간 문의 0건 누락",
    category: "챗봇",
    real: false,
    date: "2026-03-02",
  },
];
